import type { CategoryDef } from "./types.js";

/**
 * Default categories & keyword dictionary. Keywords only need their
 * canonical (accented) Vietnamese spelling — matching against a
 * non-accented or mixed-accent typing of the SAME word is handled
 * automatically by normalize.ts#wordMatches. List a separate entry only
 * for words that are genuinely different from the accented form, e.g.
 * English/abbreviation slang ("cf", "grab") or brand names.
 */
export const DEFAULT_CATEGORIES: CategoryDef[] = [
  {
    id: "food",
    name: "Ăn uống",
    emoji: "🍜",
    type: "expense",
    keywords: [
      "phở",
      "bún",
      "bún bò",
      "bún chả",
      "bún đậu",
      "bún riêu",
      "cơm",
      "cơm tấm",
      "cơm văn phòng",
      "cơm trưa văn phòng",
      "bánh mì",
      "xôi",
      "lẩu",
      "nướng",
      "bbq",
      "ăn sáng",
      "ăn trưa",
      "ăn tối",
      "ăn vặt",
      "đi chợ",
      "chợ",
      "quán ăn",
      "nhà hàng",
      "cơm nhà",
      "mì",
      "mì tôm",
      "miến",
      "hủ tiếu",
      "cháo",
      "bánh cuốn",
      "bánh xèo",
      "bánh canh",
      "gỏi cuốn",
      "chả cá",
      "gà rán",
      "kfc",
      "lotteria",
      "pizza",
      "mcdonald",
      "burger",
      "sandwich",
      "salad",
      "đồ ăn",
      "thịt",
      "cá",
      "rau củ",
      "hải sản",
      "ốc",
      "buffet",
      "ăn hàng",
      "đi ăn",
    ],
  },
  {
    id: "drinks",
    name: "Cà phê & đồ uống",
    emoji: "☕",
    type: "expense",
    keywords: [
      "cafe",
      "cà phê",
      "cf",
      "cfe",
      "coffee",
      "highlands",
      "starbucks",
      "phúc long",
      "trung nguyên",
      "the coffee house",
      "trà đá",
      "trà sữa",
      "trà chanh",
      "trà",
      "nước",
      "nước ngọt",
      "sinh tố",
      "nước ép",
      "bia",
      "rượu",
      "cocktail",
      "milo",
      "matcha",
      "chè",
      "sữa chua",
      "yaourt",
    ],
  },
  {
    id: "transport",
    name: "Đi lại",
    emoji: "🛵",
    type: "expense",
    keywords: [
      "xăng",
      "grab",
      "grabbike",
      "grabcar",
      "be",
      "xanh sm",
      "xanhsm",
      "taxi",
      "gửi xe",
      "vé xe",
      "rửa xe",
      "sửa xe",
      "gojek",
      "xe ôm",
      "vé máy bay",
      "máy bay",
      "tàu",
      "xe khách",
      "bến xe",
      "đổ xăng",
      "phí cầu đường",
      "đăng kiểm",
      "bảo dưỡng xe",
      "thay nhớt",
      "vé tàu",
    ],
  },
  {
    id: "housing",
    name: "Nhà cửa",
    emoji: "🏠",
    type: "expense",
    keywords: [
      "tiền nhà",
      "tiền trọ",
      "đồ gia dụng",
      "nội thất",
      "sửa nhà",
      "thuê nhà",
      "phí quản lý",
      "phí dịch vụ chung cư",
      "sửa chữa nhà",
    ],
  },
  {
    id: "bills",
    name: "Hóa đơn",
    emoji: "💡",
    type: "expense",
    keywords: [
      "tiền điện",
      "tiền nước",
      "internet",
      "wifi",
      "4g",
      "5g",
      "nạp điện thoại",
      "cước điện thoại",
      "truyền hình cáp",
      "hóa đơn",
      "điện",
      "nạp thẻ điện thoại",
    ],
  },
  {
    id: "shopping",
    name: "Mua sắm",
    emoji: "🛒",
    type: "expense",
    keywords: [
      "siêu thị",
      "shopee",
      "lazada",
      "tiki",
      "quần áo",
      "giày",
      "dép",
      "túi xách",
      "mỹ phẩm",
      "nước hoa",
      "nước giặt",
      "nước mắm",
      "tạp hóa",
      "mua sắm",
      "đồ dùng",
      "văn phòng phẩm",
      "phụ kiện",
      "sách vở dụng cụ",
    ],
  },
  {
    id: "health",
    name: "Sức khỏe",
    emoji: "💊",
    type: "expense",
    keywords: [
      "thuốc",
      "khám bệnh",
      "khám",
      "nha khoa",
      "gym",
      "phòng khám",
      "bệnh viện",
      "bác sĩ",
      "spa",
      "massage",
      "vitamin",
      "nhổ răng",
      "tiêm phòng",
    ],
  },
  {
    id: "entertainment",
    name: "Giải trí",
    emoji: "🎮",
    type: "expense",
    keywords: [
      "phim",
      "cgv",
      "lotte cinema",
      "netflix",
      "spotify",
      "game",
      "du lịch",
      "karaoke",
      "bar",
      "pub",
      "vé xem phim",
      "concert",
      "sự kiện",
      "youtube premium",
      "steam",
      "apple music",
      "vé concert",
    ],
  },
  {
    id: "education",
    name: "Học tập",
    emoji: "📚",
    type: "expense",
    keywords: ["sách", "khóa học", "học phí", "học liệu", "bút vở", "du học", "dạy thêm", "gia sư", "học online"],
  },
  {
    id: "gifts",
    name: "Hiếu hỉ & quà",
    emoji: "🎁",
    type: "expense",
    keywords: [
      "mừng cưới",
      "đám cưới",
      "quà",
      "sinh nhật",
      "biếu",
      "phúng viếng",
      "đám ma",
      "mừng tân gia",
      "lì xì",
      "quà tặng",
    ],
  },
  {
    id: "other",
    name: "Khác",
    emoji: "❓",
    type: "expense",
    keywords: [],
    isFallback: true,
  },
  {
    id: "salary",
    name: "Lương",
    emoji: "💰",
    type: "income",
    keywords: ["lương", "lương tháng", "lương cứng"],
  },
  {
    id: "bonus",
    name: "Thưởng",
    emoji: "🎉",
    type: "income",
    keywords: ["thưởng", "tiền thưởng", "hoa hồng", "thưởng tết", "thưởng dự án"],
  },
  {
    id: "other_income",
    name: "Thu khác",
    emoji: "💵",
    type: "income",
    keywords: ["hoàn tiền", "được cho", "được tặng", "cashback", "tiền lãi", "thu nhập khác", "bán đồ"],
    isFallback: true,
  },
];

/** Keywords that, when found anywhere in a message, mark the whole item as income (before category matching). */
export const INCOME_SIGNAL_KEYWORDS: string[] = [
  "lương",
  "thưởng",
  "hoàn tiền",
  "được cho",
  "được tặng",
  "cashback",
  "tiền lãi",
];
